field_07_spec = {
"01":  {"data_enc": "ascii", "len_enc": "ascii", "len_type": 0, "max_len": 2, "desc": "Month"},
"02":  {"data_enc": "ascii", "len_enc": "ascii", "len_type": 0, "max_len": 2, "desc": "Day"},
"03":  {"data_enc": "ascii", "len_enc": "ascii", "len_type": 0, "max_len": 6, "desc": "Time"},
}

field_12_spec = {
"01":  {"data_enc": "ascii", "len_enc": "ascii", "len_type": 0, "max_len": 2, "desc": "Year"},
"02":  {"data_enc": "ascii", "len_enc": "ascii", "len_type": 0, "max_len": 2, "desc": "Month"},
"03":  {"data_enc": "ascii", "len_enc": "ascii", "len_type": 0, "max_len": 2, "desc": "Day"},
"04":  {"data_enc": "ascii", "len_enc": "ascii", "len_type": 0, "max_len": 6, "desc": "Time"},
}

field_22_spec = {
"01":  {"data_enc": "ascii", "len_enc": "ascii", "len_type": 0, "max_len": 1, "desc": "Card Data Input Capability"},
"02":  {"data_enc": "ascii", "len_enc": "ascii", "len_type": 0, "max_len": 1, "desc": "Cardholder Authentication Capability"},
"03":  {"data_enc": "ascii", "len_enc": "ascii", "len_type": 0, "max_len": 1, "desc": "Card Capture Capability"},
"04":  {"data_enc": "ascii", "len_enc": "ascii", "len_type": 0, "max_len": 1, "desc": "Operating Environment"},
"05":  {"data_enc": "ascii", "len_enc": "ascii", "len_type": 0, "max_len": 1, "desc": "Cardholder Present"},
"06":  {"data_enc": "ascii", "len_enc": "ascii", "len_type": 0, "max_len": 1, "desc": "Card Present"},
"07":  {"data_enc": "ascii", "len_enc": "ascii", "len_type": 0, "max_len": 1, "desc": "Card Data Input Mode"},
"08":  {"data_enc": "ascii", "len_enc": "ascii", "len_type": 0, "max_len": 1, "desc": "Cardmember Authentication Method"},
"09":  {"data_enc": "ascii", "len_enc": "ascii", "len_type": 0, "max_len": 1, "desc": "Cardmember Authentication Entity"},
"10":  {"data_enc": "ascii", "len_enc": "ascii", "len_type": 0, "max_len": 1, "desc": "Card Data Output Capability"},
"11":  {"data_enc": "ascii", "len_enc": "ascii", "len_type": 0, "max_len": 1, "desc": "Terminal Output Capability"},
"12":  {"data_enc": "ascii", "len_enc": "ascii", "len_type": 0, "max_len": 1, "desc": "PIN Capture Capability"},
}

field_55_spec = {
"00":  {"data_enc": "ascii", "len_enc": "ascii", "len_type": 0, "max_len": 12, "desc": "ICC Header"},
"01":  {"data_enc": "ascii", "len_enc": "ascii", "len_type": 0, "max_len": 16, "desc": "Application Cryptogram"},
"02":  {"data_enc": "ascii", "len_enc": "ascii", "len_type": 2, "max_len": 99, "desc": "Issuer Application Data (IAD)"},
"03":  {"data_enc": "ascii", "len_enc": "ascii", "len_type": 0, "max_len": 8,  "desc": "Unpredictable Number"},
"04":  {"data_enc": "ascii", "len_enc": "ascii", "len_type": 0, "max_len": 4,  "desc": "ATC"},
"05":  {"data_enc": "ascii", "len_enc": "ascii", "len_type": 0, "max_len": 10, "desc": "Terminal Verification Results (TVR)"},
"06":  {"data_enc": "ascii", "len_enc": "ascii", "len_type": 0, "max_len": 6,  "desc": "Transaction Date"},
"07":  {"data_enc": "ascii", "len_enc": "ascii", "len_type": 0, "max_len": 2,  "desc": "Transaction Type"},
"08":  {"data_enc": "ascii", "len_enc": "ascii", "len_type": 0, "max_len": 12, "desc": "Amount Authorized"},
"09":  {"data_enc": "ascii", "len_enc": "ascii", "len_type": 0, "max_len": 4,  "desc": "Transaction Currency Code"},
"10":  {"data_enc": "ascii", "len_enc": "ascii", "len_type": 0, "max_len": 4,  "desc": "Terminal Country Code"},
"11":  {"data_enc": "ascii", "len_enc": "ascii", "len_type": 0, "max_len": 4,  "desc": "Application Interchange Profile (AIP)"},
"12":  {"data_enc": "ascii", "len_enc": "ascii", "len_type": 0, "max_len": 12, "desc": "Amount, Other"},
"13":  {"data_enc": "ascii", "len_enc": "ascii", "len_type": 0, "max_len": 2,  "desc": "Application PAN Sequence Number"},
"14":  {"data_enc": "ascii", "len_enc": "ascii", "len_type": 0, "max_len": 2,  "desc": "Cryptogram Information Data (CID)"},
}

spec = {
"h":      {"data_enc": "cp500", "len_enc": "cp500", "len_type": 0, "max_len": 0,   "desc": "Message Header"},
"t":      {"data_enc": "cp500", "len_enc": "cp500", "len_type": 0, "max_len": 4,   "desc": "Message Type"},
"p":      {"data_enc": "b",     "len_enc": "cp500", "len_type": 0, "max_len": 8,   "desc": "Bitmap, Primary"},
"1":      {"data_enc": "b",     "len_enc": "cp500", "len_type": 0, "max_len": 8,   "desc": "Bitmap, Secondary"},
"2":      {"data_enc": "cp500", "len_enc": "cp500", "len_type": 2, "max_len": 19,  "desc": "Primary Account Number (PAN)"},
"3":      {"data_enc": "cp500", "len_enc": "cp500", "len_type": 0, "max_len": 6,   "desc": "Processing Code"},
"4":      {"data_enc": "cp500", "len_enc": "cp500", "len_type": 0, "max_len": 12,  "desc": "Amount, Transaction"},
"7":      {"data_enc": "cp500", "len_enc": "cp500", "len_type": 0, "max_len": 10,  "desc": "Date And Time, Transmission", "sub_field_specs": field_07_spec}, 
"11":     {"data_enc": "cp500", "len_enc": "cp500", "len_type": 0, "max_len": 6,   "desc": "System Trace Audit Number"},
"12":     {"data_enc": "cp500", "len_enc": "cp500", "len_type": 0, "max_len": 12,  "desc": "Date and Time, Local Transaction", "sub_field_specs": field_12_spec},
"13":     {"data_enc": "cp500", "len_enc": "cp500", "len_type": 0, "max_len": 4,   "desc": "Date Effective"},
"14":     {"data_enc": "cp500", "len_enc": "cp500", "len_type": 0, "max_len": 4,   "desc": "Date, Expiration"},
"15":     {"data_enc": "cp500", "len_enc": "cp500", "len_type": 0, "max_len": 6,   "desc": "Date, Settlement"},
"19":     {"data_enc": "cp500", "len_enc": "cp500", "len_type": 0, "max_len": 3,   "desc": "Acquiring Institution Country Code"},
"22":     {"data_enc": "cp500", "len_enc": "cp500", "len_type": 0, "max_len": 12,  "desc": "Point Of Service Data Code", "sub_field_specs": field_22_spec},
"24":     {"data_enc": "cp500", "len_enc": "cp500", "len_type": 0, "max_len": 3,   "desc": "Function Code"},
"25":     {"data_enc": "cp500", "len_enc": "cp500", "len_type": 0, "max_len": 4,   "desc": "Message Reason Code"},
"26":     {"data_enc": "cp500", "len_enc": "cp500", "len_type": 0, "max_len": 4,   "desc": "Card Acceptor Business Code"},
"27":     {"data_enc": "cp500", "len_enc": "cp500", "len_type": 0, "max_len": 1,   "desc": "Approval Code Length"},
"30":     {"data_enc": "cp500", "len_enc": "cp500", "len_type": 0, "max_len": 24,  "desc": "Amounts, Original"},
"31":     {"data_enc": "cp500", "len_enc": "cp500", "len_type": 2, "max_len": 48,  "desc": "Acquirer Reference"},
"32":     {"data_enc": "cp500", "len_enc": "cp500", "len_type": 2, "max_len": 11,  "desc": "Acquiring Institution ID Code"},
"33":     {"data_enc": "cp500", "len_enc": "cp500", "len_type": 2, "max_len": 11,  "desc": "Forwarding Institution ID Code"},
"34":     {"data_enc": "cp500", "len_enc": "cp500", "len_type": 2, "max_len": 28,  "desc": "Primary Account Number, Extended"},
"35":     {"data_enc": "cp500", "len_enc": "cp500", "len_type": 2, "max_len": 37,  "desc": "Track 2 Data"},
"37":     {"data_enc": "cp500", "len_enc": "cp500", "len_type": 0, "max_len": 12,  "desc": "Retrieval Reference Number"},
"38":     {"data_enc": "cp500", "len_enc": "cp500", "len_type": 0, "max_len": 6,   "desc": "Approval Code"},
"39":     {"data_enc": "cp500", "len_enc": "cp500", "len_type": 0, "max_len": 3,   "desc": "Action Code"},
"41":     {"data_enc": "cp500", "len_enc": "cp500", "len_type": 0, "max_len": 8,   "desc": "Card Acceptor Terminal ID"},
"42":     {"data_enc": "cp500", "len_enc": "cp500", "len_type": 0, "max_len": 15,  "desc": "Card Acceptor ID Code"},
"43":     {"data_enc": "cp500", "len_enc": "cp500", "len_type": 2, "max_len": 99,  "desc": "Card Acceptor Name/Location"},
"44":     {"data_enc": "cp500", "len_enc": "cp500", "len_type": 2, "max_len": 25,  "desc": "Additional Response Data"},
"45":     {"data_enc": "cp500", "len_enc": "cp500", "len_type": 2, "max_len": 76,  "desc": "Track 1 Data"},
"47":     {"data_enc": "cp500", "len_enc": "cp500", "len_type": 3, "max_len": 301, "desc": "Additional Data, National"},
"48":     {"data_enc": "cp500", "len_enc": "cp500", "len_type": 3, "max_len": 40,  "desc": "Additional Data, Private"},
"49":     {"data_enc": "cp500", "len_enc": "cp500", "len_type": 0, "max_len": 3,   "desc": "Currency Code, Transaction"},
"52":     {"data_enc": "b",     "len_enc": "cp500", "len_type": 0, "max_len": 8,   "desc": "PIN data"},
"53":     {"data_enc": "cp500", "len_enc": "cp500", "len_type": 2, "max_len": 17,  "desc": "Security Releated Control Information"},
"54":     {"data_enc": "cp500", "len_enc": "cp500", "len_type": 3, "max_len": 120, "desc": "Amounts Additional"},
"55":     {"data_enc": "b",     "len_enc": "cp500", "len_type": 3, "max_len": 256, "desc": "ICC data", "sub_field_specs": field_55_spec},
"56":     {"data_enc": "cp500", "len_enc": "cp500", "len_type": 2, "max_len": 35,  "desc": "Original Data Elements"},
"60":     {"data_enc": "cp500", "len_enc": "cp500", "len_type": 3, "max_len": 141, "desc": "National Use Data 60"},
"61":     {"data_enc": "cp500", "len_enc": "cp500", "len_type": 3, "max_len": 100, "desc": "National Use Data 61"},
"62":     {"data_enc": "cp500", "len_enc": "cp500", "len_type": 3, "max_len": 60,  "desc": "Private Use Data 62"},
"63":     {"data_enc": "cp500", "len_enc": "cp500", "len_type": 3, "max_len": 205, "desc": "Private Use Data 63"},
"96":     {"data_enc": "b",     "len_enc": "cp500", "len_type": 3, "max_len": 999, "desc": "Key Management Data"},
"111":    {"data_enc": "b",     "len_enc": "cp500", "len_type": 4, "max_len": 958, "desc": "Encryption Data"},
"112":    {"data_enc": "cp500", "len_enc": "cp500", "len_type": 3, "max_len": 79,  "desc": "Payment Account Data"},
"113":    {"data_enc": "cp500", "len_enc": "cp500", "len_type": 3, "max_len": 15,  "desc": "Acceptance Environment Indicator"},
}



